# Generated by Django 4.2.1 on 2023-06-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.TextField()),
                ('birthday', models.DateField()),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
