# Generated by Django 4.2.1 on 2023-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='motto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
